In [2]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

df = pd.read_excel("data/employee_dataset_clean.xlsx")
df.head()

,employeeid,age,department,joblevel,yearsatcompany,monthlyincome,jobsatisfaction,worklifebalance,overtime,distancefromhome,promotionlast5years,performancerating,traininghourslastyear,attrition,age_group
0,EMP0000,42,Sales,3,9,9866,4,1,No,24.5,Yes,4,19,No,Middle age
1,EMP0001,36,Sales,3,7,8958,3,3,No,10.0,No,2,13,No,Middle age
2,EMP0002,44,Sales,4,16,11716,4,3,No,4.0,No,4,13,No,Senior
3,EMP0003,53,Finance,4,30,17061,5,3,No,7.1,No,3,20,No,Senior
4,EMP0004,35,HR,2,4,5738,2,3,No,8.4,No,2,15,No,Middle age

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   employeeid             10000 non-null  str
 1   age                    10000 non-null  int64
 2   department             10000 non-null  str
 3   joblevel               10000 non-null  int64
 4   yearsatcompany         10000 non-null  int64
 5   monthlyincome          10000 non-null  int64
 6   jobsatisfaction        10000 non-null  int64
 7   worklifebalance        10000 non-null  int64
 8   overtime               10000 non-null  str
 9   distancefromhome       10000 non-null  float64
 10  promotionlast5years    10000 non-null  str
 11  performancerating      10000 non-null  int64
 12  traininghourslastyear  10000 non-null  int64
 13  attrition              10000 non-null  str
 14  age_group              10000 non-null  str
dtypes: float64(1), int64(8), str(6)
memory usage: 1.1 MB

In [4]:
df.shape

(10000, 15)

In [12]:
df.dtypes

employeeid                    str
age                         int64
department                    str
joblevel                    int64
yearsatcompany              int64
monthlyincome               int64
jobsatisfaction             int64
worklifebalance             int64
overtime                      str
distancefromhome          float64
promotionlast5years           str
performancerating           int64
traininghourslastyear       int64
attrition                     str
age_group                category
dtype: object

In [5]:
df.describe(include='all')

,employeeid,age,department,joblevel,yearsatcompany,monthlyincome,jobsatisfaction,worklifebalance,overtime,distancefromhome,promotionlast5years,performancerating,traininghourslastyear,attrition,age_group
count,10000,10000.000000,10000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000,10000.00000,10000,10000.000000,10000.000000,10000,10000
unique,10000,NaN,7,NaN,NaN,NaN,NaN,NaN,2,NaN,2,NaN,NaN,2,3
top,EMP0000,NaN,Sales,NaN,NaN,NaN,NaN,NaN,No,NaN,No,NaN,NaN,No,Middle age
freq,1,NaN,2453,NaN,NaN,NaN,NaN,NaN,7151,NaN,9086,NaN,NaN,9097,3493
mean,NaN,37.693500,NaN,2.380800,7.788400,8967.918800,3.362100,2.761500,NaN,9.91074,NaN,2.603800,14.993100,NaN,NaN
std,NaN,9.376457,NaN,1.141368,7.141941,3500.745748,1.059951,0.893027,NaN,6.97463,NaN,0.737889,3.886227,NaN,NaN
min,NaN,22.000000,NaN,1.000000,0.000000,3000.000000,1.000000,1.000000,NaN,1.00000,NaN,1.000000,2.000000,NaN,NaN
25%,NaN,31.000000,NaN,1.000000,2.000000,6043.500000,3.000000,2.000000,NaN,4.70000,NaN,2.000000,12.000000,NaN,NaN
50%,NaN,37.000000,NaN,2.000000,6.000000,8670.000000,3.000000,3.000000,NaN,8.30000,NaN,3.000000,15.000000,NaN,NaN
75%,NaN,44.000000,NaN,3.000000,12.000000,11484.000000,4.000000,3.000000,NaN,13.40000,NaN,3.000000,18.000000,NaN,NaN
max,NaN,60.000000,NaN,5.000000,35.000000,21410.000000,5.000000,4.000000,NaN,50.00000,NaN,4.000000,31.000000,NaN,NaN

In [6]:
df.isnull().sum()    # checks is there any null value

employeeid               0
age                      0
department               0
joblevel                 0
yearsatcompany           0
monthlyincome            0
jobsatisfaction          0
worklifebalance          0
overtime                 0
distancefromhome         0
promotionlast5years      0
performancerating        0
traininghourslastyear    0
attrition                0
age_group                0
dtype: int64

In [7]:
df.columns =df.columns.str.lower()  # lower case

In [13]:
# Number of unique values in each column
df.nunique()

employeeid               10000
age                         39
department                   7
joblevel                     5
yearsatcompany              36
monthlyincome             6784
jobsatisfaction              5
worklifebalance              4
overtime                     2
distancefromhome           381
promotionlast5years          2
performancerating            4
traininghourslastyear       30
attrition                    2
age_group                    3
dtype: int64

In [8]:
df.columns

Index(['employeeid', 'age', 'department', 'joblevel', 'yearsatcompany',
       'monthlyincome', 'jobsatisfaction', 'worklifebalance', 'overtime',
       'distancefromhome', 'promotionlast5years', 'performancerating',
       'traininghourslastyear', 'attrition', 'age_group'],
      dtype='str')

In [9]:
#create a column for age group

labels = ['Adult','Middle age','Senior']
df ['age_group'] =pd.qcut(df['age'],q=3,labels=labels)
df[['age','age_group']].head(15)

    age   age_group
0    42  Middle age
1    36  Middle age
2    44      Senior
3    53      Senior
4    35  Middle age
5    35  Middle age
6    53      Senior
7    45      Senior
8    33       Adult
9    43      Senior
10   33       Adult
11   33       Adult
12   40  Middle age
13   22       Adult
14   22       Adult

In [10]:
df.duplicated().sum() # check for any dublicates

np.int64(0)

In [11]:
df['distancefromhome'].head(10)

0    24.5
1    10.0
2     4.0
3     7.1
4     8.4
5     3.1
6     8.9
7    17.6
8     3.6
9     8.6
Name: distancefromhome, dtype: float64

In [14]:
# Memory usage
df.memory_usage(deep=True)

Index                       132
employeeid               560000
age                       80000
department               561369
joblevel                  80000
yearsatcompany            80000
monthlyincome             80000
jobsatisfaction           80000
worklifebalance           80000
overtime                 512849
distancefromhome          80000
promotionlast5years      510914
performancerating         80000
traininghourslastyear     80000
attrition                510903
age_group                 10168
dtype: int64

In [16]:
df.describe(include=['object', 'string'])

       employeeid department overtime promotionlast5years attrition
count       10000      10000    10000               10000     10000
unique      10000          7        2                   2         2
top       EMP0000      Sales       No                  No        No
freq            1       2453     7151                9086      9097